# Generated by Django 3.2 on 2022-09-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Music',
            new_name='music',
        ),
    ]
