# Generated by Django 3.2 on 2022-09-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rename_music_review_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
    ]
