# Generated by Django 3.2 on 2022-09-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_and_likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dishes',
            new_name='music',
        ),
    ]
